config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :stories do
  	resources :reviews
  end
  root 'stories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :stories
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :story
	belongs_to :user
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :story_img, styles: { story_index: "250x350>", story_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :story_img, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stories
	has_many :reviews
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		   :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_story
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.story_id = @story.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to story_path(@story)
		else
			render 'new'
		end
	end

	def edit	
	end

	def update
		if @review.update(review_params)
			redirect_to story_path(@story)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to story_path(@story)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_story
			@story = Story.find(params[:story_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :find_story, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:category].blank?
			@stories = Story.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@stories = Story.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if @story.reviews.blank?
			@average_review = 0
		else
			@average_review = @story.reviews.average(:rating).round(2)
		end
	end

	def new
		@story = current_user.stories.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@story = current_user.stories.build(story_params)
		@story.category_id = params[:category_id]

		if @story.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@story.category_id = params[:category_id]

		if @story.update(story_params)
			redirect_to story_path(@story)
		else
			render 'edit'
		end
	end

	def destroy
		@story.destroy
		redirect_to root_path
	end

	private

		def story_params
			params.require(:story).permit(:title, :description, :creator, :category_id, :story_img)
		end

		def find_story
			@story = Story.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Branddify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Branddify", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
			</ul>

			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sort <span class="caret"></span></a>

					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, stories_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>

				<% if user_signed_in? %>
					<li><%= link_to "Add Story", new_story_path %></li>
				<% end %>
			</ul>
		</div>
	</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@story, @story.reviews.build]) do |f| %>
	<div id="rating-form">
		<label> Rating </label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, class: "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
			<div class="links btn-group">
				<%= link_to "Edit", edit_story_review_path(review.story, review), class: "btn btn-custom" %>
				<%= link_to "Delete", story_review_path(review.story, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-offset-1">
	<div class="edit-review-form">
		<h1> Edit Review </h1>
			<%= simple_form_for([@story, @review]) do |f| %>
				<div id="rating-form">
					<label> Rating </label>
				</div>
				<%= f.input :comment %>
				<%= f.button :submit, class: "btn-custom2" %>
			<% end %>
	</div>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-offset-1">
	<div class="new-review-form">
		<h1> Post Review </h1>
		<%= render 'form' %>
	</div>
</div>

app/views/stories/_form.html.erb
<%= simple_form_for @story do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
	<%= f.file_field :story_img %>
	<%= f.input :title, label: "Story Title" %>
	<%= f.input :description %>
	<%= f.input :creator %>
	<%= f.button :submit %>
<% end %>

app/views/stories/edit.html.erb
<h1> Edit Your Story </h1>

<%= simple_form_for @story, html: {multipart: true} do |f| %>
	<%= f.select :category_id, @categories %>
	<%= f.file_field :story_img %>
	<%= f.input :title, label: "Story Title" %>
	<%= f.input :description %>
	<%= f.input :creator %>
	<%= f.button :submit %>
<% end %>

app/views/stories/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @stories.count == 0 %>
	<h3> There are no stories in this category </h3>
<% else %>
	<div class="row">
		<% @stories.each do |story| %>
			<div class="col-md-3">
				<a href="/stories/ <%= story.id %>">
					<%= image_tag story.story_img.url(:story_index), class: "story" %>
				</a>
			</div>
		<% end %>
	</div>
<% end %>

app/views/stories/new.html.erb
<h1>New Branddify Story</h1>

<%= render 'form' %>

app/views/stories/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @story.story_img.url(:story_show), class: "story-show" %>
	</div>

	<div class="col-md-8">
		<div class="story-info">
			<h2 class="story-title"><%= @story.title %></h2>
			<h3 class="story-creator"><span><em> From: </em></span><%= @story.creator %></h3>
			<h4 class="story-category"><%= @story.category.name %></h4>
			<h4 class="avg-rating">Average Rating</h4>
			<div class="average-review-rating" data-score="<%= @average_review %>"></div>
			<span class="number-of-reviews"> <em> From: </em> <%= @story.reviews.count %> reviews </span>
			<p class="story-desc"><%= @story.description %></p>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="reviews">
			<h1> Reviews </h1>
				<%= render @story.reviews %>
				<div>
					<%= link_to "Add Reviews", new_story_review_path(@story), class: "btn-custom" %>
				</div>
		</div>
	</div>
</div>

<div class="links btn-group">
	<% if user_signed_in? %>
		<% if @story.user_id == current_user.id %>
			<%= link_to "Edit", edit_story_path(@story), class: "btn btn-custom" %>
			<%= link_to "Delete", story_path(@story), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
		<% end %>
	<% end %>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>